### ISSUE TITLE
How to pull data updates?

### ISSUE THREAD

**Issue by afonsovj** [okomarov/wrds#9]
This is brilliant but how could I introduce the ability to download data for just one period? For example, in case I want to download only an yearly update or split my request in smaller pieces?

**Comment by okomarov** [comment]
Hi, what do you mean by yearly update or by splitting the request in smaller pieces?

Can you describe a specific use case?

Also note that wrds provides an official  API to connect through matlab and build SQL queries, but is obviously much slower than this package.

Sent from my iPhone

On 11 Oct 2016, at 23:18, "afonsovj" <notifications@github.com<mailto:notifications@github.com>> wrote:

This is brilliant but how could I introduce the ability to download data for just one period? For example, in case I want to download only an yearly update or split my request in smaller pieces?

##

**Comment by afonsovj** [comment]
Hi Oleg, I mean that it would be great to have the ability to request a download of a subset of a database.dataset. For example, OptionMetrics distributes large files. It would be great if I could get data for the latest year of the Implied Vol Dataset (lets say June 2015 to 2016) and append it to my existing data, of just download it by pieces and save monthly files? Maybe this is bad data management on my part.

I tried Matlab's API but to be honest yours is more robust. Can you explain me why your's is faster?

Also, I had to change something in your code for it to work on my mac. I think I had to remove that data\ bit. Error below.

Thanks!

```
Error using ssh2_main (line 169)

Error Transferring File
SEE JAVA ERROR BELOW

Java exception occurred:
java.io.IOException: Error during SCP transfer.
    at ch.ethz.ssh2.SCPClient.get(SCPClient.java:703)
    at ch.ethz.ssh2.SCPClient.get(SCPClient.java:596)
Caused by: java.io.FileNotFoundException: /Users/[MyUserName and folder path]/data\/dataset.zip (No such file or directory)
    at java.io.FileOutputStream.open(Native Method)
    at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
    at java.io.FileOutputStream.<init>(FileOutputStream.java:171)
    at ch.ethz.ssh2.SCPClient.receiveFiles(SCPClient.java:344)
    at ch.ethz.ssh2.SCPClient.get(SCPClient.java:699)
    ... 1 more

Error in ssh2 (line 84)
    ssh2_struct = ssh2_main(ssh2_struct);

Error in scp (line 19)
    ssh2_struct = ssh2(ssh2_struct);

Error in scp_get (line 50)
    ssh2_struct = scp(ssh2_struct);

Error in wrds/getFile (line 114)
            obj.SSH2conn = scp_get(obj.SSH2conn, [rfname, rext], lpath, rpath);

Error in sas2csv (line 43)
wrds.getFile('~/tmp/dataset.zip', outfile);

Error in wrds/getDataset (line 14)
sas2csv(wrds, libdataname, outfile);
```

**Comment by okomarov** [comment]
I thought about implementing some sort of file splitter to download chunk of datasets, however, that would require some considerable work and my subscription to wrds expires in december. 

The suite is faster because it converts their raw sas datasets into compressed csvs and sends over that stream. No java encapsulation, no other interfaces or additional overhead. 

I will look into the data\ error though

**Comment by okomarov** [comment]
@afonsovj I should have fixed the data\ problem.

For the partial dataset download, do you feel the problem is that Matlab hungs for several hours until the download is complete, right? The issue with this, is potential crashes and unexpected interruptions to this operation.
The solutions are:
- do nothing and just keep one Matlab session open, potentially overnight, and work in another Matlab instance
- implement an asynchronous download request which launches a matlab session on the background

Both those cases however would benefit from a file splitting procedure that could recover from the last downloaded part, if things went wrong. 

If you are interested in working on this task, you can issue a pull request to this submission. I can help with guiding you through the code and suggesting which direction to take. The task would require getting acquainted with a bit of Unix shell commands, a bit of SAS (I sought help on their forums) and the Matlab codebase.
